### PR TITLE
Organization: make usesSAML field optional when deserializing

### PR DESCRIPTION
**Pull request by cnr**

### CODE REVIEW

**Comment by zlav** [comment]
If we can add tests for this API deserialization that would be really helpful in preventing errors like this in the future.

**Comment by cnr** [comment]
I'm not sure how to best handle cases like this -- because this deserialization will always work on up-to-date fossa instances. The issue we're seeing is from customers with out-of-date onprem instances

**Comment by scruffystuffs** [comment]
I thought I added this into the original PR.  I think I forgot to re-add after fixing some stuff up.

**Review by scruffystuffs — APPROVED** [review]
Looks Good

**Pull request merged**
