### PR TITLE
Minor: Updates pip_install req file format link

### PR DESCRIPTION
**Pull request by meghfossa**
# Overview

_Provide an overview of this change. Describe the intent of this change, and how it implements that intent._

It updates external dead link associated in python's strategy documentation.

## Acceptance criteria

_What is this PR trying to accomplish?_

Update the documentation for setuptools strategies.

## Testing plan

_How did you validate that this PR works? How did you check that the acceptance criteria were fulfilled?_

This affects documentation only. I confirmed the new link leads to intended documentation. 

Old: https://web.archive.org/web/20210421213342/https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format
New: https://pip.pypa.io/en/stable/cli/pip_install/#requirements-file-format

_This section should list reproduction steps that a reviewer can run through (and provide any needed test cases)._

N/A

## Risks

_Highlight any areas that you're unsure of, or want reviewers to pay particular attention to._

N/A

## References

_List any referenced GitHub issues. If PR references tickets in other systems (e.g. Zendesk), they should probably be mirrored as a GitHub Issue._

_Make sure to use keywords to link this PR to GitHub issues ([GitHub Docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))._

_Example:_ Closes org/repo#123.

N/A

## Checklist

- [x] I added tests for this PR's change (or confirmed tests are not viable).
- [x] I linted and formatted (via `haskell-language-server`) any haskell files I touched in this PR.
- [x] If this PR introduced a user-visible change, I added documentation into `docs/`.
- [ ] I updated `Changelog.md` if this change is externally facing. If this PR did not mark a release, I added my changes into an `# Unreleased` section at the top.
- [x] I linked this PR to any referenced GitHub issues, if they exist.

### CODE REVIEW

**Comment by meghfossa** [comment]
For following: `I updated `Changelog.md` if this change is externally facing. If this PR did not mark a release, I added my changes into an `# Unreleased` section at the top.` I can use some guidance here. Do we count docs updates to be external?

**Comment by spatten** [comment]
> For following: `I updated `Changelog.md`if this change is externally facing. If this PR did not mark a release, I added my changes into an`# Unreleased` section at the top.` I can use some guidance here. Do we count docs updates to be external?

I'm not sure what the answer to this is. @liftM should a change to a URL in documentation be added to the changelog?

**Review by spatten — APPROVED** [review]
Other than your question about whether this needs to be added to the changelog, this looks good to me.

**Comment by liftM** [comment]
LGTM. I would not generally consider doc updates to be user-facing, although obviously exercise judgement for large changes and ask when unsure. Good catch on the dead link!

**Comment by liftM** [comment]
@meghfossa the intention for the "user facing" part of the checklist is so when we cut a new release, customers have release notes before they install the new version. This is why I'm not really worried about doc changes.

**Comment by scruffystuffs** [comment]
Yeah, I would say doc changes that require changelog entries are usually major changes, or documenting previously undocumented features.  And even that second one is not really that necessary.

**Comment by scruffystuffs** [comment]
Can you rebase this PR on latest master and merge it?

**Pull request merged**
