### PR TITLE
Minor: Alphabetizes analyze's discovery functions

### PR DESCRIPTION
**Pull request by meghfossa**
# Overview

It alphabetizes analyze's discovery functions. 

## Acceptance criteria

_What is this PR trying to accomplish?_

It improves code readability. 

## Testing plan

_How did you validate that this PR works? How did you check that the acceptance criteria were fulfilled?_

I ran unit tests. Since it's so minor, I'm not sure there would be any additional ACs.

## Risks

_Highlight any areas that you're unsure of, or want reviewers to pay particular attention to._

I'm not 100% certain if the order of the discovery functions, have any implications on inner workings or workings. I would like someone to verify this.

## References

_List any referenced GitHub issues. If PR references tickets in other systems (e.g. Zendesk), they should probably be mirrored as a GitHub Issue._

None.

_Make sure to use keywords to link this PR to GitHub issues ([GitHub Docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))._

_Example:_ Closes org/repo#123.

N/A

## Checklist

- [x] I added tests for this PR's change (or confirmed tests are not viable).
- [x] I linted and formatted (via `haskell-language-server`) any haskell files I touched in this PR.
- [x] If this PR introduced a user-visible change, I added documentation into `docs/`.
- [x] I updated `Changelog.md` if this change is externally facing. If this PR did not mark a release, I added my changes into an `# Unreleased` section at the top.
- [x] I linked this PR to any referenced GitHub issues, if they exist.

### CODE REVIEW

**Comment by meghfossa** [comment]
I'm not clear on following requirement: `If this PR did not mark a release, I added my changes into an # Unreleased section at the top.` Does this mean I need to make PR title #Unreleased?

**Comment by scruffystuffs** [comment]
That line refers to the changelog.  This doesn't require a changelog update at all.

**Review by zlav — APPROVED** [review]
Looks great to me!

**Comment by scruffystuffs** [comment]
I'd also add a comment, saying that we keep it alphabetized for organization.  Helps the next person remember to add new bits in alphabetical order.

**Comment by scruffystuffs** [comment]
Can you rebase this PR on latest master and merge it?

**Pull request merged**
